#!/usr/bin/env sh
#
# Create and rename one font style according to the specs
# Example invocation:
#   do_generate 01 --powerline --mono CascadiaCodePL-Regular.ttf DelugiaPowerline.ttf Delugia Regular PL-Mono
#
# No parameters are checked, but they are:
# 1: Number of logfile
# 2: Conversion spec #1
# 3: Conversion spec #2
# 4: Input font file name
# 5: Output font file name
# 6: Font family (and base name)

set -e

if [ "$#" -ne 6 ]; then
    exit 1
fi

PWD=$( pwd )
outdir="${6}"

if [ ! -d "$outdir" ]; then
    mkdir "$outdir"
fi

# rm -f C*.ttf >>> remnant from delugia-font repo

fontforge -script "${PWD}/font-patcher" --debug 2 --careful "${3}" --custom SomeExtraSymbols.sfd --has-no-italic "${PWD}/${4}" "${2}" --outputdir "${PWD}" --makegroups 4 --name "${5}" | tee "process${1}.log"

if [ -z "${OURVERSION}" ]; then
    # Github CI sets this variable, but this can be useful for manual calls:
    OURVERSION=`git describe --always --tags`
fi

fontforge -script "${PWD}/rename-font" --orig "${PWD}/${4}" --input "${PWD}/${5}.ttf" --output "${PWD}/$outdir/${5}.tff" --version "${OURVERSION}" --name "${6}"
