name: Nerd Font Patcher

on:
  workflow_dispatch:
  push:
#    branches:
#      - master
    tags:
      - 'v*'
  #pull_request:
  #  branches:
  #   - master
  # schedule:
  #   - cron: "0 13 * * *"

jobs:
  check-for-new-reddit-sans:
    runs-on: ubuntu-22.04
    outputs:
      tag_name: ${{ env.REDDITSANSTAG }}
      tag_exists: ${{ steps.check_tag.outputs.exists }}

    steps:
    - uses: oprypin/find-latest-tag@v1
      with:
        repository: reddit/redditsans  # The repository to scan.
        releases-only: false  # We know that all relevant tags have a GitHub release for them.
      id: find-latest-tag  # The step ID to refer to later.
  
    - run: echo "Reddit Sans Mono is at version ${{ steps.find-latest-tag.outputs.tag }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Save the latest Reddit Sans tag
      run: |
        echo "REDDITSANSTAG=${{ steps.find-latest-tag.outputs.tag_name }}" >> $GITHUB_ENV
    - name: Check if tag exists
      uses: mukunku/tag-exists-action@v1.6.0
      id: check_tag
      with:
        tag: ${{ env.REDDITSANSTAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Summary
      run: |
        echo "Latest Reddit Sans tag is $REDDITSANSTAG"

  build-and-release:
    needs: check-for-new-reddit-sans
    if: ${{ github.event_name != 'schedule' || needs.check-for-new-reddit-sans.outputs.tag_exists != 'true' }}
    runs-on: ubuntu-22.04
    env:
      REDDITSANSTAG: ${{ needs.check-for-new-reddit-sans.outputs.tag_name }}
      REDDITSANSTAG_ISNOTNEW: ${{ needs.check-for-new-reddit-sans.outputs.tag_exists }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Decide on version
      run: |
        if [ "${REDDITSANSTAG_ISNOTNEW}" = "false" ]; then
          echo New release is not tagged yet in our repo
          echo It will only be tagged after successfull release in job 'Create tag'
          OURVERSION=${REDDITSANSTAG}
        else
          echo Re-release uses our manual tags and/or patchlevel
          OURVERSION=`git describe --always --tags`
        fi
        echo "OURVERSION=${OURVERSION}" >> $GITHUB_ENV

    - name: Download latest version of Reddit Sans Mono
      # with:
        # tag: ${{ needs.check-for-new-reddit-sans.outputs.tag_name }}
      run: |
        cURL -L https://github.com/reddit/redditsans/raw/refs/heads/main/fonts/mono/ttf/RedditMono-Regular.ttf
        cURL -L https://github.com/reddit/redditsans/raw/refs/heads/main/fonts/mono/ttf/RedditMono-Light.ttf
        cURL -L https://github.com/reddit/redditsans/raw/refs/heads/main/fonts/mono/ttf/RedditMono-Medium.ttf
        cURL -L https://github.com/reddit/redditsans/raw/refs/heads/main/fonts/mono/ttf/RedditMono-SemiBold.ttf
        cURL -L https://github.com/reddit/redditsans/raw/refs/heads/main/fonts/mono/ttf/RedditMono-Bold.ttf
        cURL -L https://github.com/reddit/redditsans/raw/refs/heads/main/fonts/mono/ttf/RedditMono-ExtraBold.ttf

    # Ubuntu 20.04 has only fontforge release 2020, but there are some vital bugfixes in the 2022 release
    # This can be replaced with the ordinary apt package when Ubuntu updates, probably with 22.10?
    # On the other hand ... why not be on the latest release always?
    - name: Fetch FontForge
      run: |
        sudo apt install software-properties-common python3-fontforge fuse -y -q
        curl -L "https://github.com/fontforge/fontforge/releases/download/20230101/FontForge-2023-01-01-a1dad3e-x86_64.AppImage" \
          --output fontforge
        chmod u+x fontforge
        echo Try appimage
        ./fontforge --version
        export PATH=`pwd`:$PATH
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo Try appimage with path
        fontforge --version

    - name: Get Font Patcher
      uses: robinraju/release-downloader@v1.10
      with:
        repository: "ryanoasis/nerd-fonts"
        latest: true
        fileName: "FontPatcher.zip"

    - name: Open Font Patcher release
      run: |
        unzip FontPatcher.zip

    - name: Install PIP
      run: sudo apt install python3-pip -y
    - name: Install configparser
      run: pip3 install configparser
    - name: Extract additional powerline glyphs
      run: fontforge -lang=ff -script "`pwd`/extract-extra-glyphs" "`pwd`" `pwd`/src/glyphs/octicons/octicons.ttf

    - name: Build Mono Powerline
      run: |
        ./do_generate 01 --powerline --mono RedditSansMono-Regular.ttf    ReaditSansMonoPL.ttf            "Readit Sans Mono PL"
        ./do_generate 02 --powerline --mono RedditSansMono-Bold.ttf       ReaditSansMonoPL-Bold.ttf       "Readit Sans Mono PL"
        ./do_generate 03 --powerline --mono RedditSansMono-SemiBold.ttf   ReaditSansMonoPL-SemiBold.ttf   "Readit Sans Mono PL"
        ./do_generate 04 --powerline --mono RedditSansMono-ExtraBold.ttf  ReaditSansMonoPL-ExtraBold.ttf  "Readit Sans Mono PL"
        ./do_generate 05 --powerline --mono RedditSansMono-Light.ttf      ReaditSansMonoPL-Light.ttf      "Readit Sans Mono PL"
        ./do_generate 06 --powerline --mono RedditSansMono-Medium.ttf     ReaditSansMonoPL-Medium.ttf     "Readit Sans Mono PL"
        mkdir readit-sans-mono-powerline
        mv Readit*ttf readit-sans-mono-powerline
        zip readit-sans-mono-powerline.zip readit-sans-mono-powerline/*

    - name: Build Mono
      run: |
        ./do_generate 07 -c --mono RedditSansMono-Regular.ttf             ReaditSansMono.ttf              "Readit Sans Mono"
        ./do_generate 08 -c --mono RedditSansMono-Bold.ttf                ReaditSansMono-Bold.ttf         "Readit Sans Mono"
        ./do_generate 09 -c --mono RedditSansMono-SemiBold.ttf            ReaditSansMono-SemiBold.ttf     "Readit Sans Mono"
        ./do_generate 10 -c --mono RedditSansMono-ExtraBold.ttf           ReaditSansMono-ExtraBold.ttf    "Readit Sans Mono"
        ./do_generate 11 -c --mono RedditSansMono-Light.ttf               ReaditSansMono-Light.ttf        "Readit Sans Mono"
        ./do_generate 12 -c --mono RedditSansMono-Medium.ttf              ReaditSansMono-Medium.ttf       "Readit Sans Mono"
        mkdir readit-sans-mono
        mv Readit*ttf readit-sans-mono
        zip readit-sans-mono.zip readit-sans-mono/*


    - name: Check for preexisting glyphs
      run: |
        grep 'Skipping...' process*.log | grep  -vE ' Powerline(Extra)?Symbols>'

    - uses: actions/upload-artifact@v4
      with:
        name: Readit Sans Mono Powerline
        path: "readit-sans-mono-powerline"

    - uses: actions/upload-artifact@v4
      with:
        name: Readit Sans Mono
        path: "readit-sans-mono"

    # Release part
    - name: Create tag
      if: ${{ github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/tags/') && needs.check-for-new-reddit-sans.outputs.tag_exists != 'true' }}
      uses: EndBug/latest-tag@latest
      with:
        ref: ${{ needs.check-for-new-reddit-sans.outputs.tag_name }}
        description: "Bump Readit Sans version to ${{ needs.check-for-new-reddit-sans.outputs.tag_name }}"

    - name: Get tag name
      id: get_tag_name
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: battila7/get-version-action@v2

    - name: Release
      uses: softprops/action-gh-release@v2
      if: ${{ github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/') || needs.check-for-new-reddit-sans.outputs.tag_exists != 'true') }}
      with:
        tag_name: ${{ startsWith(github.ref, 'refs/tags/') && steps.get_tag_name.outputs.version || needs.check-for-new-reddit-sans.outputs.tag_name }}
        files: |
          readit-sans-mono-powerline.zip
          readit-sans-mono.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
